name: Lint and test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }} test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: 2.6
            env:
              NONE: true
          - ruby-version: 2.7
            env:
              NONE: true
          - ruby-version: 3.0
            env:
              NONE: true
          - ruby-version: 3.1
            env:
              NONE: true
          - ruby-version: 3.2
            env:
              NONE: true
      fail-fast: false
    env: ${{ matrix.env }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Run RSpec
        run: bundle exec rspec

      - name: Run Rubocop
        run: bundle exec rubocop --format github
